services:
  - type: web
    name: gestore-spese
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gestore-spese-db
          property: connectionString

databases:
  - name: gestore-spese-db
    plan: free
